services:
  Dbp\Relay\BlobConnectorCampusonlineDmsBundle\Rest\:
    resource: '../../Rest'
    autowire: true
    autoconfigure: true

  Dbp\Relay\BlobConnectorCampusonlineDmsBundle\Service\:
    resource: '../../Service'
    autowire: true
    autoconfigure: true

  Dbp\Relay\BlobConnectorCampusonlineDmsBundle\Authorization\AuthorizationService:
    autowire: true
    autoconfigure: true
